### ISSUE TITLE
Cannot compile with libxml2 >= 2.12

### ISSUE THREAD

**Issue by BRA1L0R** [NVIDIA/attestation-sdk#8]
```
/home/pietro/c/attestation-sdk/nv-attestation-sdk-cpp/src/rim.cpp: In static member function ‘static nvattestation::Error nvattestation::RimDocument::create_from_rim_data(const std::string&, nvattestation::RimDocument&)’:
/home/pietro/c/attestation-sdk/nv-attestation-sdk-cpp/src/rim.cpp:64:48: error: invalid conversion from ‘const xmlError*’ {aka ‘const _xmlError*’} to ‘xmlErrorPtr’ {aka ‘_xmlError*’} [-fpermissive]
   64 |         xmlErrorPtr xml_error = xmlGetLastError();
      |                                 ~~~~~~~~~~~~~~~^~
      |                                                |
      |                                                const xmlError* {aka const _xmlError*}
make[2]: *** [CMakeFiles/nvat.dir/build.make:331: CMakeFiles/nvat.dir/src/rim.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:369: CMakeFiles/nvat.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

As described in similar issues: (https://github.com/OSGeo/gdal/issues/8746)

> A change of constness in the argument of the callback changes its type (in C++ at least), so there's no way of supporting before and after 2.12 with the same code.

**Comment by amshinde** [comment]
@BRA1L0R I see that you have opened PR https://github.com/NVIDIA/attestation-sdk/pull/9 to address this. Thanks for your contribution. Can you address comments in that PR so that we can move forward with it:

> This project still needs to compile with libxml versions < 2.12. Please add a version check to gate this change based on the libxml version.
> 
> Also note that we require commits to be signed off. See https://github.com/NVIDIA/attestation-sdk/blob/main/CONTRIBUTING.md#signing-your-work for more info. We're adding DCO Bot to this repo to make this more visible.

**Comment by amshinde** [comment]
Fixed in our latest release. Closing.
