### ISSUE TITLE
[Bug]: vendored fmt and spdlog are treated as first-party for warnings

### ISSUE THREAD

**Issue by quartzjer** [NVIDIA/attestation-sdk#32]
on `main` @ `73efa3ac`, a stock `USE_SYSTEM_DEPS=OFF` build on macOS 26.5 / AppleClang 21.0.0 / arm64 fails at 12% building fmt. configure was clean.

<details>
<summary><code>fmt.dir/src/os.cc.o</code></summary>

```
In file included from .../fmt-src/src/os.cc:13:
In file included from .../fmt-src/include/fmt/os.h:14:
In file included from .../MacOSX26.5.sdk/usr/include/c++/v1/system_error:152:
.../c++/v1/__fwd/string_view.h:22:41: error: 'char_traits<fmt::detail::char8_type>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in a future release, so please migrate off of it. [-Werror,-Wdeprecated-declarations]
   22 | template <class _CharT, class _Traits = char_traits<_CharT> >
      |                                         ^
.../fmt-src/include/fmt/core.h:361:26: note: in instantiation of default argument for 'basic_string_view<fmt::detail::char8_type>' required here
...
```
</details>

`format.cc.o` fails the same way. the diagnostic is libc++'s. it becomes an error because `nv-attestation-sdk-cpp/CMakeLists.txt:7` sets `CMAKE_COMPILE_WARNING_AS_ERROR` before `FetchContent_MakeAvailable(fmt)` at `:112` and `(spdlog)` at `:124`, so both vendored trees are configured under the project's warnings-as-errors.

the same ownership question shows up a second time. four sites add the pinned fmt and spdlog roots as ordinary `-I` paths alongside first-party ones:

- `nv-attestation-sdk-cpp/CMakeLists.txt:355-366`
- `nv-attestation-sdk-cpp/unit-tests/CMakeLists.txt:177-181`
- `nv-attestation-cli/CMakeLists.txt:105-110`
- `nv-attestation-cli/tests/CMakeLists.txt:69-73`

so once the first is fixed, a diagnostic raised inside those headers still lands on first-party translation units.

the second isn't fixed by adding `SYSTEM` in place: it applies to the whole call, so it would mark `src`, the build-interface include and the regorus ffi root as SYSTEM too, and reorder the search path. each site needs splitting into a plain call plus a `SYSTEM` one.

we carry both fixes on a fork and can send either or both.

**Comment by amshinde** [comment]
@quartzjer Your analysis looks right. We didnt catch this on Linux as no warnings surfaced due to difference in standard library. 
In any case, sounds right to not treat warnings as errors from vendored trees.

Please send both fixes. Will be happy to take a look. Thanks!
