### ISSUE TITLE
[Bug]: vendored build fails on macOS, the SDK cmake selected never reaches the sub-builds

### ISSUE THREAD

**Issue by quartzjer** [NVIDIA/attestation-sdk#33]
on `main` @ `73efa3ac`, a stock `USE_SYSTEM_DEPS=OFF` build on macOS 26.5 / AppleClang 21.0.0 / arm64 fails in vendored OpenSSL. configure was clean.

<details>
<summary><code>crypto/aes/libcrypto-lib-aes_cbc.o</code></summary>

```
In file included from crypto/aes/aes_cbc.c:18:
In file included from include/openssl/modes.h:20:
In file included from include/openssl/types.h:32:
include/openssl/e_os2.h:203:10: fatal error: 'sys/types.h' file not found
  203 | #include <sys/types.h>
      |          ^~~~~~~~~~~~~
1 error generated.
```
</details>

cmake picked the SDK correctly: `CMAKE_OSX_SYSROOT` in the cache is the MacOSX26.5 sdk path, and `CMAKE_OSX_ARCHITECTURES` is `arm64`. neither reaches the sub-build. the OpenSSL `ExternalProject` passes `CC=${CMAKE_C_COMPILER}` and `CFLAGS=${CMAKE_C_FLAGS} -fPIC`, `CMAKE_C_FLAGS` is empty, and grepping the sub-build stamps finds no `-isysroot` and no `-arch`. so OpenSSL's configure runs a compiler with no sysroot, and macOS hasn't shipped `/usr/include` since 10.14.

the xmlsec and curl `ExternalProject`s pass no `CC` or `CFLAGS` at all, so they'd take whatever autoconf finds. OpenSSL is just the first to fail.

we ship a native arm64 macOS artifact from a fork ([solpbc/attestation-sdk](https://github.com/solpbc/attestation-sdk), branch `sol/portable`), so the plumbing exists. the upstreamable part is small: thread the sysroot and architecture cmake already selected into the vendored configure and build steps. nothing needs discovering, the values are already in the cache.

what we would not send: our fork also hard-fails configure on anything but native single-arch arm64, and enumerates OpenSSL `Configure` target triples with a `FATAL_ERROR` on anything unlisted. both are right for our release build and wrong here. you pass no target and let OpenSSL detect, which covers triples we would break.

the readme doesn't list macOS, so this may simply be out of scope. if it is, say so and we'll keep carrying it. we can test arm64 macOS and linux x86_64/aarch64, and we have no Intel Mac.
